/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiPublicAgentJobsRouteImport } from './routes/api/public/agent/jobs'
import { Route as ApiPublicAgentResultsRouteImport } from './routes/api/public/agent/results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentJobsRoute = ApiPublicAgentJobsRouteImport.update({
  id: '/api/public/agent/jobs',
  path: '/api/public/agent/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentResultsRoute = ApiPublicAgentResultsRouteImport.update({
  id: '/api/public/agent/results',
  path: '/api/public/agent/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/agent/jobs': typeof ApiPublicAgentJobsRoute
  '/api/public/agent/results': typeof ApiPublicAgentResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/agent/jobs': typeof ApiPublicAgentJobsRoute
  '/api/public/agent/results': typeof ApiPublicAgentResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/agent/jobs': typeof ApiPublicAgentJobsRoute
  '/api/public/agent/results': typeof ApiPublicAgentResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/api/public/agent/jobs' | '/api/public/agent/results'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/api/public/agent/jobs' | '/api/public/agent/results'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/public/agent/jobs'
    | '/api/public/agent/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiPublicAgentJobsRoute: typeof ApiPublicAgentJobsRoute
  ApiPublicAgentResultsRoute: typeof ApiPublicAgentResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/jobs': {
      id: '/api/public/agent/jobs'
      path: '/api/public/agent/jobs'
      fullPath: '/api/public/agent/jobs'
      preLoaderRoute: typeof ApiPublicAgentJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/results': {
      id: '/api/public/agent/results'
      path: '/api/public/agent/results'
      fullPath: '/api/public/agent/results'
      preLoaderRoute: typeof ApiPublicAgentResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiPublicAgentJobsRoute: ApiPublicAgentJobsRoute,
  ApiPublicAgentResultsRoute: ApiPublicAgentResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
